apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-for-backend-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JeremyArc/argocd-application-on-eks.git
    targetRevision: HEAD
    path: backend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-backend

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
