apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-for-frontend-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JeremyArc/argocd-application-on-eks.git
    targetRevision: HEAD
    path: frontend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-frontend

  # CreateNamespace = true => when argocd try to deploy application if there are not defined namespace,
  # argocd will automatically create it.
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
